name: Deploy

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 1 * *'  # Keep it up-to-date automatically (monthly)

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push containers
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm,linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ghcr.io/tonyduckles/website-server:latest
